version: '3.8'
services:
  server:
    container_name: server
    restart: unless-stopped
    build: ./server
    ports:
      - "${PORT:-8081}:${PORT:-8081}"
    depends_on:
      - db
    volumes:
      - ./server:/usr/src/app
    networks:
      - scraper

  db:
    container_name: db
    restart: unless-stopped
    image: postgres
    ports:
      - '5433:${DB_PORT:-5432}'
    volumes:
      - ./.docker/db/data:/data/db
    environment:
      POSTGRES_DB: ${DB_DATABASE:-master}
      POSTGRES_USER: ${DB_USER:-admin}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-secret}
      POSTGRES_ROOT_PASSWORD: ${DB_PASSWORD:-secret}
    networks:
      - scraper

  pgadmin:
    container_name: pgadmin
    restart: unless-stopped
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin

    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - scraper

networks:
  scraper:
    driver: bridge

volumes:
  data:
  pgadmin: